insert into dist_batch_statuses_flow ([dist_batch_statuses_id], [user_role_id], [flow_dist_batch_statuses_id], [flow_dist_batch_type_id], [main_menu_id], [sub_menu_id], [sub_menu_order], [reject_dist_batch_statuses_id], [flow_dist_card_statuses_id], [reject_dist_card_statuses_id], [branch_card_statuses_id], [reject_branch_card_statuses_id], [dist_batch_status_flow_id]) values( -1, 5, 0, 0, 1, null, 0, null, null, null, null, null, 7)
insert into dist_batch_statuses_flow ([dist_batch_statuses_id], [user_role_id], [flow_dist_batch_statuses_id], [flow_dist_batch_type_id], [main_menu_id], [sub_menu_id], [sub_menu_order], [reject_dist_batch_statuses_id], [flow_dist_card_statuses_id], [reject_dist_card_statuses_id], [branch_card_statuses_id], [reject_branch_card_statuses_id], [dist_batch_status_flow_id]) values( -1, 5, 0, 0, 1, null, 0, null, null, null, null, null, 8)

insert into dist_batch_statuses_flow ([dist_batch_statuses_id], [user_role_id], [flow_dist_batch_statuses_id], [flow_dist_batch_type_id], [main_menu_id], [sub_menu_id], [sub_menu_order], [reject_dist_batch_statuses_id], [flow_dist_card_statuses_id], [reject_dist_card_statuses_id], [branch_card_statuses_id], [reject_branch_card_statuses_id], [dist_batch_status_flow_id]) values( 0, 4, 21, 0, 1, null, 2, 8, null, null, null, null, 7)
insert into dist_batch_statuses_flow ([dist_batch_statuses_id], [user_role_id], [flow_dist_batch_statuses_id], [flow_dist_batch_type_id], [main_menu_id], [sub_menu_id], [sub_menu_order], [reject_dist_batch_statuses_id], [flow_dist_card_statuses_id], [reject_dist_card_statuses_id], [branch_card_statuses_id], [reject_branch_card_statuses_id], [dist_batch_status_flow_id]) values( 0, 4, 21, 0, 1, null, 2, 8, null, null, null, null, 8)

insert into dist_batch_statuses_flow ([dist_batch_statuses_id], [user_role_id], [flow_dist_batch_statuses_id], [flow_dist_batch_type_id], [main_menu_id], [sub_menu_id], [sub_menu_order], [reject_dist_batch_statuses_id], [flow_dist_card_statuses_id], [reject_dist_card_statuses_id], [branch_card_statuses_id], [reject_branch_card_statuses_id], [dist_batch_status_flow_id]) values( 9, 12, 23, 0, 1, null, 4, null, null, null, null, null, 7)
insert into dist_batch_statuses_flow ([dist_batch_statuses_id], [user_role_id], [flow_dist_batch_statuses_id], [flow_dist_batch_type_id], [main_menu_id], [sub_menu_id], [sub_menu_order], [reject_dist_batch_statuses_id], [flow_dist_card_statuses_id], [reject_dist_card_statuses_id], [branch_card_statuses_id], [reject_branch_card_statuses_id], [dist_batch_status_flow_id]) values( 18, 12, 23, 0, 1, null, 4, null, null, null, null, null, 8)

insert into dist_batch_statuses_flow ([dist_batch_statuses_id], [user_role_id], [flow_dist_batch_statuses_id], [flow_dist_batch_type_id], [main_menu_id], [sub_menu_id], [sub_menu_order], [reject_dist_batch_statuses_id], [flow_dist_card_statuses_id], [reject_dist_card_statuses_id], [branch_card_statuses_id], [reject_branch_card_statuses_id], [dist_batch_status_flow_id]) values(10, 12, 24, 0, 1, null, 5, null, null, null, null, null, 7)
insert into dist_batch_statuses_flow ([dist_batch_statuses_id], [user_role_id], [flow_dist_batch_statuses_id], [flow_dist_batch_type_id], [main_menu_id], [sub_menu_id], [sub_menu_order], [reject_dist_batch_statuses_id], [flow_dist_card_statuses_id], [reject_dist_card_statuses_id], [branch_card_statuses_id], [reject_branch_card_statuses_id], [dist_batch_status_flow_id]) values( 10, 12, 24, 0, 1, null, 5, null, null, null, null, null, 8)
