:r .\dbo.mac_index_keys_cards.sql
:r .\dbo.mac_index_keys_users.sql
:r .\dbo.fileloader_status.sql
:r .\dbo.auth_configuration.sql
:r .\dbo.printer.sql
:r .\dbo.issuer.sql
:r .\dbo.branch.sql
:r .\dbo.user_admin.sql
:r .\dbo.user_group.sql
:r .\dbo.user.sql
:r .\dbo.users_to_users_groups.sql