CREATE TABLE [dbo].[issuer_product] (
    [product_id]                          INT             IDENTITY (1, 1) NOT NULL,
    [product_code]                        VARCHAR (50)    NOT NULL,
    [product_name]                        VARCHAR (100)   NOT NULL,
    [product_bin_code]                    VARCHAR (15)    NOT NULL,
    [issuer_id]                           INT             NOT NULL,
    [name_on_card_top]                    DECIMAL (8, 2)  NULL,
    [name_on_card_left]                   DECIMAL (8, 2)  NULL,
    [Name_on_card_font_size]              INT             NULL,
    [font_id]                             INT             NULL,
    [DeletedYN]                           BIT             NULL,
    [src1_id]                             INT             NOT NULL,
    [src2_id]                             INT             NOT NULL,
    [src3_id]                             INT             NOT NULL,
    [PVKI]                                VARBINARY (MAX) NULL,
    [PVK]                                 VARBINARY (MAX) NULL,
    [CVKA]                                VARBINARY (MAX) NULL,
    [CVKB]                                VARBINARY (MAX) NULL,
    [expiry_months]                       INT             NULL,
    [fee_scheme_id]                       INT             NULL,
    [enable_instant_pin_YN]               BIT             NOT NULL,
    [min_pin_length]                      INT             NOT NULL,
    [max_pin_length]                      INT             NOT NULL,
    [enable_instant_pin_reissue_YN]       BIT             NOT NULL,
    [cms_exportable_YN]                   BIT             NOT NULL,
    [product_load_type_id]                INT             NOT NULL,
    [sub_product_code]                    VARCHAR (4)     NULL,
    [pin_calc_method_id]                  INT             NOT NULL,
    [auto_approve_batch_YN]               BIT             NOT NULL,
    [account_validation_YN]               BIT             NOT NULL,
    [pan_length]                          SMALLINT        NOT NULL,
    [pin_mailer_printing_YN]              BIT             NOT NULL,
    [pin_mailer_reprint_YN]               BIT             NOT NULL,
    [sub_product_id]                      INT             NULL,
    [master_product_id]                   INT             NULL,
    [card_issue_method_id]                INT             NOT NULL,
    [decimalisation_table]                VARBINARY (MAX) NULL,
    [pin_validation_data]                 VARBINARY (MAX) NULL,
    [pin_block_formatid]                  INT             NULL,
    [production_dist_batch_status_flow]   INT             NOT NULL,
    [distribution_dist_batch_status_flow] INT             NOT NULL,
    [charge_fee_to_issuing_branch_YN]     BIT             NOT NULL,
    [print_issue_card_YN]                 BIT             DEFAULT ((1)) NOT NULL,
    [allow_manual_uploaded_YN]            BIT             CONSTRAINT [DF_issuer_product_allow_manual_uploaded_YN] DEFAULT ((0)) NOT NULL,
    [allow_reupload_YN]                   BIT             CONSTRAINT [DF_issuer_product_allow_reupload_YN] DEFAULT ((0)) NOT NULL,
    [remote_cms_update_YN] BIT NOT NULL DEFAULT 0, 
	[charge_fee_at_cardrequest]           BIT             NULL,
    [e_pin_request_YN]                    BIT             CONSTRAINT [DF_issuer_product_e_pin_request_YN] DEFAULT ((0)) NULL,

    CONSTRAINT [PK_issuer_product] PRIMARY KEY CLUSTERED ([product_id] ASC),
    CONSTRAINT [chkPinMinLength] CHECK ([max_pin_length]>=[min_pin_length]),
    CONSTRAINT [chkPinMinMaxLength] CHECK ([min_pin_length]>=(4)),
    CONSTRAINT [CK_BIN_LENGTH] CHECK ([product_bin_code] IS NOT NULL AND len([product_bin_code])=(6)),
    CONSTRAINT [CK_BIN_SUBPRODUCT] CHECK ([dbo].[ProductValidation]([product_id],[product_bin_code],[sub_product_code])=(1)),
    CONSTRAINT [FK_issuer_product_pin_block_format] FOREIGN KEY ([pin_block_formatid]) REFERENCES [dbo].[pin_block_format] ([pin_block_formatid]),
    CONSTRAINT [FK_issuer_product_product_service_request_1] FOREIGN KEY ([src1_id]) REFERENCES [dbo].[product_service_requet_code1] ([src1_id]),
    CONSTRAINT [FK_issuer_product_product_service_request_2] FOREIGN KEY ([src2_id]) REFERENCES [dbo].[product_service_requet_code2] ([src2_id]),
    CONSTRAINT [FK_issuer_product_product_service_request_3] FOREIGN KEY ([src3_id]) REFERENCES [dbo].[product_service_requet_code3] ([src3_id]),
    CONSTRAINT [FK_dist_batch_status_flow_issuer_product] FOREIGN KEY ([production_dist_batch_status_flow]) REFERENCES [dbo].[dist_batch_status_flow] ([dist_batch_status_flow_id]),
    CONSTRAINT [FK_issuer_product_issuer] FOREIGN KEY ([issuer_id]) REFERENCES [dbo].[issuer] ([issuer_id]),
    CONSTRAINT [FK_issuer_product_Issuer_product_font] FOREIGN KEY ([font_id]) REFERENCES [dbo].[Issuer_product_font] ([font_id]),
    CONSTRAINT [FK_issuer_product_pin_calc_methods] FOREIGN KEY ([pin_calc_method_id]) REFERENCES [dbo].[pin_calc_methods] ([pin_calc_method_id]),
    CONSTRAINT [FK_issuer_product_product_batch_type] FOREIGN KEY ([product_load_type_id]) REFERENCES [dbo].[product_load_type] ([product_load_type_id]),
    CONSTRAINT [FK_product_fee_scheme] FOREIGN KEY ([fee_scheme_id]) REFERENCES [dbo].[product_fee_scheme] ([fee_scheme_id]),
    CONSTRAINT [FK_product_issue_method] FOREIGN KEY ([card_issue_method_id]) REFERENCES [dbo].[card_issue_method] ([card_issue_method_id]),
    CONSTRAINT [FK_production_dist_batch_status_flow_issuer_product] FOREIGN KEY ([distribution_dist_batch_status_flow]) REFERENCES [dbo].[dist_batch_status_flow] ([dist_batch_status_flow_id])
);

