//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch_statuses
    {
        public branch_statuses()
        {
            this.branches = new HashSet<branch>();
            this.branch_statuses_language = new HashSet<branch_statuses_language>();
        }
    
        public int branch_status_id { get; set; }
        public string branch_status { get; set; }
    
        public virtual ICollection<branch> branches { get; set; }
        public virtual ICollection<branch_statuses_language> branch_statuses_language { get; set; }
    }
}
