
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    using System.Collections.Generic;
    
public partial class branch
{

    public int branch_id { get; set; }

    public int branch_status_id { get; set; }

    public int issuer_id { get; set; }

    public string branch_code { get; set; }

    public string branch_name { get; set; }

    public string location { get; set; }

    public string contact_person { get; set; }

    public string contact_email { get; set; }

    public string card_centre { get; set; }

    public string emp_branch_code { get; set; }

    public Nullable<int> branch_type_id { get; set; }

    public Nullable<int> main_branch_id { get; set; }



    public virtual issuer issuer { get; set; }

}

}
