
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class CardSearchResult
{

    public Nullable<int> TOTAL_PAGES { get; set; }

    public Nullable<long> ROW_NO { get; set; }

    public Nullable<int> TOTAL_ROWS { get; set; }

    public long card_id { get; set; }

    public string card_number { get; set; }

    public string card_request_reference { get; set; }

    public int product_id { get; set; }

    public int card_issue_method_id { get; set; }

    public int card_priority_id { get; set; }

    public int branch_card_statuses_id { get; set; }

    public string current_card_status { get; set; }

    public Nullable<long> operator_user_id { get; set; }

    public Nullable<System.DateTime> status_date { get; set; }

    public string operator_username { get; set; }

    public string product_bin_code { get; set; }

    public int issuer_id { get; set; }

    public string issuer_name { get; set; }

    public string branch_name { get; set; }

    public string issuer_code { get; set; }

    public string branch_code { get; set; }

    public int branch_id { get; set; }

    public string comments { get; set; }

    public string sub_product_code { get; set; }

}

}
