
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class CardHistoryReference
{

    public string branch_card_statuses_name { get; set; }

    public Nullable<System.DateTime> status_date { get; set; }

    public string username { get; set; }

}

}
