
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class CardHistoryStatus
{

    public string dist_batch_reference { get; set; }

    public string dist_batch_type_name { get; set; }

    public long dist_batch_id { get; set; }

    public Nullable<System.DateTime> date_created { get; set; }

}

}
