//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class card_issue_reason
    {
        public card_issue_reason()
        {
            this.card_issue_reason_language = new HashSet<card_issue_reason_language>();
            this.customer_account = new HashSet<customer_account>();
        }
    
        public int card_issue_reason_id { get; set; }
        public string card_issuer_reason_name { get; set; }
    
        public virtual ICollection<card_issue_reason_language> card_issue_reason_language { get; set; }
        public virtual ICollection<customer_account> customer_account { get; set; }
    }
}
