//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class connection_parameter_type
    {
        public connection_parameter_type()
        {
            this.connection_parameter_type_language = new HashSet<connection_parameter_type_language>();
            this.connection_parameters1 = new HashSet<connection_parameters>();
        }
    
        public int connection_parameter_type_id { get; set; }
        public string connection_parameter_type_name { get; set; }
    
        public virtual ICollection<connection_parameter_type_language> connection_parameter_type_language { get; set; }
        public virtual ICollection<connection_parameters> connection_parameters1 { get; set; }
    }
}
