//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_title
    {
        public customer_title()
        {
            this.customer_account = new HashSet<customer_account>();
            this.customer_title_language = new HashSet<customer_title_language>();
        }
    
        public int customer_title_id { get; set; }
        public string customer_title_name { get; set; }
    
        public virtual ICollection<customer_account> customer_account { get; set; }
        public virtual ICollection<customer_title_language> customer_title_language { get; set; }
    }
}
