
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class DistBatchCardDetail
{

    public string card_number { get; set; }

    public string dist_card_status_name { get; set; }

    public int product_id { get; set; }

    public string product_code { get; set; }

    public string product_name { get; set; }

    public string product_bin_code { get; set; }

    public int issuer_id { get; set; }

    public Nullable<long> customer_account_id { get; set; }

    public Nullable<long> user_id { get; set; }

    public long card_id { get; set; }

    public Nullable<int> account_type_id { get; set; }

    public Nullable<int> currency_id { get; set; }

    public Nullable<int> resident_id { get; set; }

    public Nullable<int> customer_type_id { get; set; }

    public string customer_account_number { get; set; }

    public string customer_first_name { get; set; }

    public string customer_middle_name { get; set; }

    public string customer_last_name { get; set; }

    public string name_on_card { get; set; }

    public Nullable<System.DateTime> date_issued { get; set; }

    public string cms_id { get; set; }

    public string contract_number { get; set; }

    public Nullable<int> customer_title_id { get; set; }

    public string Id_number { get; set; }

    public string contact_number { get; set; }

    public int branch_id { get; set; }

    public int card_issue_method_id { get; set; }

    public int card_priority_id { get; set; }

    public string card_request_reference { get; set; }

    public int card_sequence { get; set; }

    public Nullable<System.DateTime> card_activation_date { get; set; }

    public Nullable<System.DateTime> card_expiry_date { get; set; }

    public Nullable<System.DateTime> card_production_date { get; set; }

    public string pvv { get; set; }

    public long dist_batch_id { get; set; }

    public int dist_card_status_id { get; set; }

    public int src1_id { get; set; }

    public int src2_id { get; set; }

    public int src3_id { get; set; }

    public Nullable<int> PVKI { get; set; }

    public string PVK { get; set; }

    public string CVKA { get; set; }

    public string CVKB { get; set; }

    public Nullable<int> expiry_months { get; set; }

    public string CustomerId { get; set; }

    public string issuer_code { get; set; }

    public string issuer_name { get; set; }

    public string branch_code { get; set; }

    public string branch_name { get; set; }

    public string card_reference_number { get; set; }

    public string dist_batch_reference { get; set; }

    public string sub_product_code { get; set; }

    public short pan_length { get; set; }

    public string delivery_branch_code { get; set; }

    public string delivery_branch_name { get; set; }

}

}
