//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dist_batch_statuses
    {
        public dist_batch_statuses()
        {
            this.dist_batch_status = new HashSet<dist_batch_status>();
            this.dist_batch_statuses_language = new HashSet<dist_batch_statuses_language>();
        }
    
        public int dist_batch_statuses_id { get; set; }
        public string dist_batch_status_name { get; set; }
        public Nullable<int> dist_batch_expected_statuses_id { get; set; }
    
        public virtual ICollection<dist_batch_status> dist_batch_status { get; set; }
        public virtual ICollection<dist_batch_statuses_language> dist_batch_statuses_language { get; set; }
    }
}
