//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dist_batch_status
    {
        public long dist_batch_status_id { get; set; }
        public long dist_batch_id { get; set; }
        public int dist_batch_statuses_id { get; set; }
        public long user_id { get; set; }
        public System.DateTime status_date { get; set; }
        public string status_notes { get; set; }
    
        public virtual dist_batch dist_batch { get; set; }
        public virtual dist_batch dist_batch1 { get; set; }
        public virtual dist_batch_statuses dist_batch_statuses { get; set; }
        public virtual user user { get; set; }
    }
}
