
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class FileHistoryResult
{

    public long file_id { get; set; }

    public Nullable<int> issuer_id { get; set; }

    public int file_status_id { get; set; }

    public int file_type_id { get; set; }

    public string name_of_file { get; set; }

    public Nullable<System.DateTime> file_created_date { get; set; }

    public int file_size { get; set; }

    public Nullable<System.DateTime> load_date { get; set; }

    public string file_directory { get; set; }

    public Nullable<int> number_successful_records { get; set; }

    public Nullable<int> number_failed_records { get; set; }

    public string file_load_comments { get; set; }

    public string file_status { get; set; }

    public string file_type { get; set; }

    public string issuer_name { get; set; }

    public string issuer_code { get; set; }

    public int file_load_id { get; set; }

}

}
