
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    using System.Collections.Generic;
    
public partial class file_types
{

    public file_types()
    {

        this.file_history = new HashSet<file_history>();

    }


    public int file_type_id { get; set; }

    public string file_type { get; set; }



    public virtual ICollection<file_history> file_history { get; set; }

}

}
