//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class integration_responses
    {
        public integration_responses()
        {
            this.integration_responses_language = new HashSet<integration_responses_language>();
        }
    
        public int integration_id { get; set; }
        public int integration_object_id { get; set; }
        public int integration_field_id { get; set; }
        public int integration_response_id { get; set; }
        public string integration_response_value { get; set; }
        public bool integration_response_valid_response { get; set; }
    
        public virtual integration_fields integration_fields { get; set; }
        public virtual ICollection<integration_responses_language> integration_responses_language { get; set; }
    }
}
