
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Issuer_product_font
{

    public int font_id { get; set; }

    public string font_name { get; set; }

    public string resource_path { get; set; }

    public Nullable<bool> DeletedYN { get; set; }



    public virtual Issuer_product_font Issuer_product_font1 { get; set; }

    public virtual Issuer_product_font Issuer_product_font2 { get; set; }

}

}
