
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class IssuerInterfaceResult
{

    public int connection_parameter_id { get; set; }

    public string connection_name { get; set; }

    public string address { get; set; }

    public int port { get; set; }

    public string path { get; set; }

    public string protocol { get; set; }

    public int auth_type { get; set; }

    public string username { get; set; }

    public string password { get; set; }

}

}
