//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class issuer_statuses
    {
        public issuer_statuses()
        {
            this.issuers = new HashSet<issuer>();
            this.issuer_statuses_language = new HashSet<issuer_statuses_language>();
        }
    
        public int issuer_status_id { get; set; }
        public string issuer_status_name { get; set; }
    
        public virtual ICollection<issuer> issuers { get; set; }
        public virtual ICollection<issuer_statuses_language> issuer_statuses_language { get; set; }
    }
}
