//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ldap_setting
    {
        public ldap_setting()
        {
            this.users = new HashSet<user>();
        }
    
        public int ldap_setting_id { get; set; }
        public string ldap_setting_name { get; set; }
        public string hostname_or_ip { get; set; }
        public string path { get; set; }
        public string domain_name { get; set; }
        public byte[] username { get; set; }
        public byte[] password { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
