
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class LoadBatchHistoryResult
{

    public string load_batch_reference { get; set; }

    public int no_cards { get; set; }

    public Nullable<System.DateTime> status_date { get; set; }

    public string load_batch_status_name { get; set; }

    public string username { get; set; }

    public string first_name { get; set; }

    public string last_name { get; set; }

}

}
