
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class LoadBatchResult
{

    public Nullable<int> TOTAL_PAGES { get; set; }

    public Nullable<long> ROW_NO { get; set; }

    public Nullable<int> TOTAL_ROWS { get; set; }

    public long load_batch_id { get; set; }

    public Nullable<System.DateTime> load_date { get; set; }

    public string load_batch_reference { get; set; }

    public int no_cards { get; set; }

    public int load_batch_statuses_id { get; set; }

    public string status_notes { get; set; }

    public string load_batch_status_name { get; set; }

    public string BranchName { get; set; }

}

}
