//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class load_batch
    {
        public load_batch()
        {
            this.load_batch_cards = new HashSet<load_batch_cards>();
            this.load_batch_status = new HashSet<load_batch_status>();
            this.load_card_failed = new HashSet<load_card_failed>();
        }
    
        public long load_batch_id { get; set; }
        public long file_id { get; set; }
        public int load_batch_status_id { get; set; }
        public int no_cards { get; set; }
        public System.DateTime load_date { get; set; }
        public string load_batch_reference { get; set; }
    
        public virtual file_history file_history { get; set; }
        public virtual load_batch_statuses load_batch_statuses { get; set; }
        public virtual ICollection<load_batch_cards> load_batch_cards { get; set; }
        public virtual load_batch load_batch1 { get; set; }
        public virtual load_batch load_batch2 { get; set; }
        public virtual ICollection<load_batch_status> load_batch_status { get; set; }
        public virtual ICollection<load_card_failed> load_card_failed { get; set; }
    }
}
