
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class notification_branch_ListResult
{

    public Nullable<int> TOTAL_PAGES { get; set; }

    public Nullable<long> ROW_NO { get; set; }

    public Nullable<int> TOTAL_ROWS { get; set; }

    public string issuer_name { get; set; }

    public string issuer_code { get; set; }

    public string branch_card_statuses_name { get; set; }

    public string card_issue_method_name { get; set; }

    public int issuer_id { get; set; }

    public int card_issue_method_id { get; set; }

    public int branch_card_statuses_id { get; set; }

    public int channel_id { get; set; }

}

}
