//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pin_batch
    {
        public pin_batch()
        {
            this.pin_batch_cards = new HashSet<pin_batch_cards>();
            this.pin_batch_status = new HashSet<pin_batch_status>();
        }
    
        public long pin_batch_id { get; set; }
        public int no_cards { get; set; }
        public System.DateTime date_created { get; set; }
        public string pin_batch_reference { get; set; }
        public int pin_batch_type_id { get; set; }
        public int card_issue_method_id { get; set; }
        public int issuer_id { get; set; }
        public Nullable<int> branch_id { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual card_issue_method card_issue_method { get; set; }
        public virtual issuer issuer { get; set; }
        public virtual ICollection<pin_batch_cards> pin_batch_cards { get; set; }
        public virtual pin_batch_type pin_batch_type { get; set; }
        public virtual ICollection<pin_batch_status> pin_batch_status { get; set; }
    }
}
