//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pin_batch_statuses
    {
        public pin_batch_statuses()
        {
            this.pin_batch_status = new HashSet<pin_batch_status>();
            this.pin_batch_statuses_language = new HashSet<pin_batch_statuses_language>();
        }
    
        public int pin_batch_statuses_id { get; set; }
        public string pin_batch_statuses_name { get; set; }
    
        public virtual ICollection<pin_batch_status> pin_batch_status { get; set; }
        public virtual ICollection<pin_batch_statuses_language> pin_batch_statuses_language { get; set; }
    }
}
