//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pin_batch_status_current
    {
        public long pin_batch_status_id { get; set; }
        public long pin_batch_id { get; set; }
        public int pin_batch_statuses_id { get; set; }
        public long user_id { get; set; }
        public System.DateTime status_date { get; set; }
        public string status_notes { get; set; }
    }
}
