
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class ProductChargeResult
{

    public int fee_detail_id { get; set; }

    public int currency_id { get; set; }

    public int card_issue_reason_id { get; set; }

    public decimal fee_charge { get; set; }

    public Nullable<System.DateTime> date_created { get; set; }

    public decimal vat { get; set; }

}

}
