
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class ProductFeeDetailsResult
{

    public int fee_scheme_id { get; set; }

    public int fee_detail_id { get; set; }

    public string fee_detail_name { get; set; }

    public bool fee_waiver_YN { get; set; }

    public bool fee_editable_YN { get; set; }

}

}
