//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_fee_detail
    {
        public product_fee_detail()
        {
            this.product_fee_charge = new HashSet<product_fee_charge>();
        }
    
        public int fee_scheme_id { get; set; }
        public int fee_detail_id { get; set; }
        public string fee_detail_name { get; set; }
        public System.DateTime effective_from { get; set; }
        public bool fee_waiver_YN { get; set; }
        public bool fee_editable_YN { get; set; }
        public bool deleted_yn { get; set; }
        public Nullable<System.DateTime> effective_to { get; set; }
    
        public virtual ICollection<product_fee_charge> product_fee_charge { get; set; }
        public virtual product_fee_scheme product_fee_scheme { get; set; }
    }
}
