
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class RemoteTokenIssuerResult
{

    public int issuer_id { get; set; }

    public string issuer_code { get; set; }

    public string issuer_name { get; set; }

    public int issuer_status_id { get; set; }

    public Nullable<System.DateTime> remote_token_expiry { get; set; }

}

}
