
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class ResponseMessageResult
{

    public string english_response { get; set; }

    public string french_response { get; set; }

    public string portuguese_response { get; set; }

    public string spanish_response { get; set; }

}

}
