
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Veneka.Indigo.Common.Models
{

using System;
    
public partial class TerminalListResult
{

    public Nullable<int> TOTAL_PAGES { get; set; }

    public Nullable<long> ROW_NO { get; set; }

    public Nullable<int> TOTAL_ROWS { get; set; }

    public int terminal_id { get; set; }

    public string terminal_name { get; set; }

    public string terminal_model { get; set; }

    public string issuer_name { get; set; }

    public string branch_name { get; set; }

    public string deviceid { get; set; }

}

}
