//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_gender
    {
        public user_gender()
        {
            this.users = new HashSet<user>();
        }
    
        public int user_gender_id { get; set; }
        public string user_gender_text { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
