//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuItems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuItems() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MenuItems", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Manager.
        /// </summary>
        internal static string AuditAdminHeading {
            get {
                return ResourceManager.GetString("AuditAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Audit Report.
        /// </summary>
        internal static string AuditAdminView {
            get {
                return ResourceManager.GetString("AuditAdminView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch NotificationList.
        /// </summary>
        internal static string BatchNotificationList {
            get {
                return ResourceManager.GetString("BatchNotificationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Branch.
        /// </summary>
        internal static string BranchAdminCreate {
            get {
                return ResourceManager.GetString("BranchAdminCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Admin.
        /// </summary>
        internal static string BranchAdminHeading {
            get {
                return ResourceManager.GetString("BranchAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Branches.
        /// </summary>
        internal static string BranchAdminManage {
            get {
                return ResourceManager.GetString("BranchAdminManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch NotificationList.
        /// </summary>
        internal static string BranchNotificationList {
            get {
                return ResourceManager.GetString("BranchNotificationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Card.
        /// </summary>
        internal static string CardActivation {
            get {
                return ResourceManager.GetString("CardActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Centralized Card.
        /// </summary>
        internal static string CardAdminCentralCard {
            get {
                return ResourceManager.GetString("CardAdminCentralCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Issuing.
        /// </summary>
        internal static string CardAdminHeading {
            get {
                return ResourceManager.GetString("CardAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Error.
        /// </summary>
        internal static string CardAdminInError {
            get {
                return ResourceManager.GetString("CardAdminInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string CardAdminInProgress {
            get {
                return ResourceManager.GetString("CardAdminInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Renewed Card.
        /// </summary>
        internal static string CardAdminIssueCardRenewal {
            get {
                return ResourceManager.GetString("CardAdminIssueCardRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Centralised Card.
        /// </summary>
        internal static string CardAdminIssueCentralisedCard {
            get {
                return ResourceManager.GetString("CardAdminIssueCentralisedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Hybrid Card.
        /// </summary>
        internal static string CardAdminIssueHybridCard {
            get {
                return ResourceManager.GetString("CardAdminIssueHybridCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Instant Card.
        /// </summary>
        internal static string CardAdminIssueInstantCard {
            get {
                return ResourceManager.GetString("CardAdminIssueInstantCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Card.
        /// </summary>
        internal static string CardAdminOrderCard {
            get {
                return ResourceManager.GetString("CardAdminOrderCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Cards.
        /// </summary>
        internal static string CardAdminReviewCards {
            get {
                return ResourceManager.GetString("CardAdminReviewCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Search.
        /// </summary>
        internal static string CardAdminSearch {
            get {
                return ResourceManager.GetString("CardAdminSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Card.
        /// </summary>
        internal static string CardManagement {
            get {
                return ResourceManager.GetString("CardManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Management.
        /// </summary>
        internal static string CardManagementHeader {
            get {
                return ResourceManager.GetString("CardManagementHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string CardProductionHeading {
            get {
                return ResourceManager.GetString("CardProductionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to CMS.
        /// </summary>
        internal static string CardProductionUpload {
            get {
                return ResourceManager.GetString("CardProductionUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work In Progress.
        /// </summary>
        internal static string CardProductionWorkInProgress {
            get {
                return ResourceManager.GetString("CardProductionWorkInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string CardRequestBatchApprove {
            get {
                return ResourceManager.GetString("CardRequestBatchApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Central Card Batch.
        /// </summary>
        internal static string CardRequestBatchCentral {
            get {
                return ResourceManager.GetString("CardRequestBatchCentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Batch.
        /// </summary>
        internal static string CardRequestBatchList {
            get {
                return ResourceManager.GetString("CardRequestBatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Batch.
        /// </summary>
        internal static string CardRequestCreateBatch {
            get {
                return ResourceManager.GetString("CardRequestCreateBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Request.
        /// </summary>
        internal static string CardRequestHeading {
            get {
                return ResourceManager.GetString("CardRequestHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Card Stock.
        /// </summary>
        internal static string CardStockOrdering {
            get {
                return ResourceManager.GetString("CardStockOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post - Production Approve.
        /// </summary>
        internal static string CardStocktBatchPostApprove {
            get {
                return ResourceManager.GetString("CardStocktBatchPostApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre - Poduction Approve.
        /// </summary>
        internal static string CardStocktBatchPreApprove {
            get {
                return ResourceManager.GetString("CardStocktBatchPreApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Error Report.
        /// </summary>
        internal static string CMSErrorReport {
            get {
                return ResourceManager.GetString("CMSErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Approval.
        /// </summary>
        internal static string DistBatchAdminApproval {
            get {
                return ResourceManager.GetString("DistBatchAdminApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Dist Batch.
        /// </summary>
        internal static string DistBatchAdminCreate {
            get {
                return ResourceManager.GetString("DistBatchAdminCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch to Branch.
        /// </summary>
        internal static string DistBatchAdminDispatch {
            get {
                return ResourceManager.GetString("DistBatchAdminDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Batch.
        /// </summary>
        internal static string DistBatchAdminHeading {
            get {
                return ResourceManager.GetString("DistBatchAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Batches.
        /// </summary>
        internal static string DistBatchAdminReceive {
            get {
                return ResourceManager.GetString("DistBatchAdminReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Batch Search.
        /// </summary>
        internal static string DistBatchAdminSearch {
            get {
                return ResourceManager.GetString("DistBatchAdminSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External System Fields.
        /// </summary>
        internal static string ExternalSystemFields {
            get {
                return ResourceManager.GetString("ExternalSystemFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create External System.
        /// </summary>
        internal static string ExternalSystems {
            get {
                return ResourceManager.GetString("ExternalSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Status Report .
        /// </summary>
        internal static string FeeStatusReport {
            get {
                return ResourceManager.GetString("FeeStatusReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Loader.
        /// </summary>
        internal static string FileLoaderAdminHeading {
            get {
                return ResourceManager.GetString("FileLoaderAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View File Loader Log.
        /// </summary>
        internal static string FileLoaderAdminView {
            get {
                return ResourceManager.GetString("FileLoaderAdminView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Load.
        /// </summary>
        internal static string FileLoadList {
            get {
                return ResourceManager.GetString("FileLoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string FundsLoadApprove {
            get {
                return ResourceManager.GetString("FundsLoadApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string FundsLoadCompleted {
            get {
                return ResourceManager.GetString("FundsLoadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string FundsLoadCreate {
            get {
                return ResourceManager.GetString("FundsLoadCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds Load.
        /// </summary>
        internal static string FundsLoadHeader {
            get {
                return ResourceManager.GetString("FundsLoadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string FundsLoadLoad {
            get {
                return ResourceManager.GetString("FundsLoadLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string FundsLoadReview {
            get {
                return ResourceManager.GetString("FundsLoadReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Issuer.
        /// </summary>
        internal static string IssuerAdminCreate {
            get {
                return ResourceManager.GetString("IssuerAdminCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer Admin.
        /// </summary>
        internal static string IssuerAdminHeading {
            get {
                return ResourceManager.GetString("IssuerAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Issuers.
        /// </summary>
        internal static string IssuerAdminManage {
            get {
                return ResourceManager.GetString("IssuerAdminManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Admin.
        /// </summary>
        internal static string LicenceAdminHeading {
            get {
                return ResourceManager.GetString("LicenceAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Licence.
        /// </summary>
        internal static string LicenceAdminIssuer {
            get {
                return ResourceManager.GetString("LicenceAdminIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence List.
        /// </summary>
        internal static string LicenceAdminList {
            get {
                return ResourceManager.GetString("LicenceAdminList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Approval.
        /// </summary>
        internal static string LoadBatchAdminAwaitingApproval {
            get {
                return ResourceManager.GetString("LoadBatchAdminAwaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Batch.
        /// </summary>
        internal static string LoadBatchAdminHeading {
            get {
                return ResourceManager.GetString("LoadBatchAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string LoadBatchAdminSearch {
            get {
                return ResourceManager.GetString("LoadBatchAdminSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Batch Notifications.
        /// </summary>
        internal static string ManageBatchNotifications {
            get {
                return ResourceManager.GetString("ManageBatchNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Branch Notifications.
        /// </summary>
        internal static string ManageBranchNotification {
            get {
                return ResourceManager.GetString("ManageBranchNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage External System Fields.
        /// </summary>
        internal static string ManageExternalSystemFields {
            get {
                return ResourceManager.GetString("ManageExternalSystemFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage External Systems.
        /// </summary>
        internal static string ManageExternalSystems {
            get {
                return ResourceManager.GetString("ManageExternalSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string MyAdminHeading {
            get {
                return ResourceManager.GetString("MyAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string MyAdminLanguage {
            get {
                return ResourceManager.GetString("MyAdminLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string MyAdminPassword {
            get {
                return ResourceManager.GetString("MyAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Authorisation Pin.
        /// </summary>
        internal static string MyAdminPinAuthorisation {
            get {
                return ResourceManager.GetString("MyAdminPinAuthorisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Batch Search.
        /// </summary>
        internal static string ProdBatchAdminSearch {
            get {
                return ResourceManager.GetString("ProdBatchAdminSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product.
        /// </summary>
        internal static string ProductsCreate {
            get {
                return ResourceManager.GetString("ProductsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Admin.
        /// </summary>
        internal static string ProductsHeading {
            get {
                return ResourceManager.GetString("ProductsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Products.
        /// </summary>
        internal static string ProductsManage {
            get {
                return ResourceManager.GetString("ProductsManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Batch.
        /// </summary>
        internal static string RenewalApproveBatch {
            get {
                return ResourceManager.GetString("RenewalApproveBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Incoming Batch.
        /// </summary>
        internal static string RenewalApproveIncomingBatch {
            get {
                return ResourceManager.GetString("RenewalApproveIncomingBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve File.
        /// </summary>
        internal static string RenewalApproveLoadedFile {
            get {
                return ResourceManager.GetString("RenewalApproveLoadedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive at Branch.
        /// </summary>
        internal static string RenewalBranchReceival {
            get {
                return ResourceManager.GetString("RenewalBranchReceival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Batch.
        /// </summary>
        internal static string RenewalCreateBatch {
            get {
                return ResourceManager.GetString("RenewalCreateBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Distribution Batch.
        /// </summary>
        internal static string RenewalDistribute {
            get {
                return ResourceManager.GetString("RenewalDistribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load File.
        /// </summary>
        internal static string RenewalFileLoad {
            get {
                return ResourceManager.GetString("RenewalFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Renewal.
        /// </summary>
        internal static string RenewalHeader {
            get {
                return ResourceManager.GetString("RenewalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Cards.
        /// </summary>
        internal static string RenewalIssueCards {
            get {
                return ResourceManager.GetString("RenewalIssueCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Card Stock.
        /// </summary>
        internal static string RenewalReceive {
            get {
                return ResourceManager.GetString("RenewalReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Incoming Batch.
        /// </summary>
        internal static string RenewalReceiveIncomingBatch {
            get {
                return ResourceManager.GetString("RenewalReceiveIncomingBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to CMS.
        /// </summary>
        internal static string RenewalUploadToCMS {
            get {
                return ResourceManager.GetString("RenewalUploadToCMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Card Renewals.
        /// </summary>
        internal static string RenewalVerifyRenewalRequest {
            get {
                return ResourceManager.GetString("RenewalVerifyRenewalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Card Stock Management Report.
        /// </summary>
        internal static string ReportBranchcardStockHeading {
            get {
                return ResourceManager.GetString("ReportBranchcardStockHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn Rate Report.
        /// </summary>
        internal static string ReportBurnRateReportHeading {
            get {
                return ResourceManager.GetString("ReportBurnRateReportHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card InProgress Report.
        /// </summary>
        internal static string ReportCardsInProgress {
            get {
                return ResourceManager.GetString("ReportCardsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Revenue Report.
        /// </summary>
        internal static string ReportFeeRevenueHeading {
            get {
                return ResourceManager.GetString("ReportFeeRevenueHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string ReportInventory {
            get {
                return ResourceManager.GetString("ReportInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Cards Summary.
        /// </summary>
        internal static string ReportIssuecardSummary {
            get {
                return ResourceManager.GetString("ReportIssuecardSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        internal static string ReportsHeading {
            get {
                return ResourceManager.GetString("ReportsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Cards.
        /// </summary>
        internal static string ReportsIssedCards {
            get {
                return ResourceManager.GetString("ReportsIssedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoil Cards Summary.
        /// </summary>
        internal static string ReportspoilcadsSummary {
            get {
                return ResourceManager.GetString("ReportspoilcadsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoil Cards Report.
        /// </summary>
        internal static string ReportSpoilCardReport {
            get {
                return ResourceManager.GetString("ReportSpoilCardReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sub Product.
        /// </summary>
        internal static string SubProductCreate {
            get {
                return ResourceManager.GetString("SubProductCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Sub Products.
        /// </summary>
        internal static string SubProductList {
            get {
                return ResourceManager.GetString("SubProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Admin.
        /// </summary>
        internal static string SystemAdminHeading {
            get {
                return ResourceManager.GetString("SystemAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Interface.
        /// </summary>
        internal static string SystemAdminInterfaceList {
            get {
                return ResourceManager.GetString("SystemAdminInterfaceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Interface.
        /// </summary>
        internal static string SystemAdminInterfaceManagement {
            get {
                return ResourceManager.GetString("SystemAdminInterfaceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage LDAP.
        /// </summary>
        internal static string SystemAdminLDAPList {
            get {
                return ResourceManager.GetString("SystemAdminLDAPList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create LDAP.
        /// </summary>
        internal static string SystemAdminLDAPManagement {
            get {
                return ResourceManager.GetString("SystemAdminLDAPManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        internal static string UserAdminCreate {
            get {
                return ResourceManager.GetString("UserAdminCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Admin.
        /// </summary>
        internal static string UserAdminHeading {
            get {
                return ResourceManager.GetString("UserAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        internal static string UserAdminManage {
            get {
                return ResourceManager.GetString("UserAdminManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Users.
        /// </summary>
        internal static string UserAdminSearch {
            get {
                return ResourceManager.GetString("UserAdminSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Admin Settings.
        /// </summary>
        internal static string UseradminSettingMaintanance {
            get {
                return ResourceManager.GetString("UseradminSettingMaintanance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Group.
        /// </summary>
        internal static string UserGroupAdminCreate {
            get {
                return ResourceManager.GetString("UserGroupAdminCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group Admin.
        /// </summary>
        internal static string UserGroupAdminHeading {
            get {
                return ResourceManager.GetString("UserGroupAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Groups.
        /// </summary>
        internal static string UserGroupAdminManage {
            get {
                return ResourceManager.GetString("UserGroupAdminManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve User Requests.
        /// </summary>
        internal static string UserPendingList {
            get {
                return ResourceManager.GetString("UserPendingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In/Out.
        /// </summary>
        internal static string VaultAdminCheckInOut {
            get {
                return ResourceManager.GetString("VaultAdminCheckInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault Management.
        /// </summary>
        internal static string VaultAdminHeading {
            get {
                return ResourceManager.GetString("VaultAdminHeading", resourceCulture);
            }
        }
    }
}
