//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veneka.Indigo.DesktopApp.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardPrintingLogicResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardPrintingLogicResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Veneka.Indigo.DesktopApp.Logic.CardPrintingLogicResource", typeof(CardPrintingLogicResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building and sending print job for printing..
        /// </summary>
        internal static string BuildPrinterJobUi {
            get {
                return ResourceManager.GetString("BuildPrinterJobUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to printer. Please printer is still available and connected to PC..
        /// </summary>
        internal static string ConnectToPrinterFailedUi {
            get {
                return ResourceManager.GetString("ConnectToPrinterFailedUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to printer..
        /// </summary>
        internal static string ConnectToPrinterSuccessUi {
            get {
                return ResourceManager.GetString("ConnectToPrinterSuccessUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to printer..
        /// </summary>
        internal static string ConnectToPrinterUi {
            get {
                return ResourceManager.GetString("ConnectToPrinterUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No print fields received to print. Please check product print field settings..
        /// </summary>
        internal static string ExceptionEmptyPrintFields {
            get {
                return ResourceManager.GetString("ExceptionEmptyPrintFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Print Details from host..
        /// </summary>
        internal static string FetchPrintJobUi {
            get {
                return ResourceManager.GetString("FetchPrintJobUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking printer&apos;s supported options for print job..
        /// </summary>
        internal static string PrinterOptionsUi {
            get {
                return ResourceManager.GetString("PrinterOptionsUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing completed, please check printer output tray..
        /// </summary>
        internal static string PrintingDoneUi {
            get {
                return ResourceManager.GetString("PrintingDoneUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing failed..
        /// </summary>
        internal static string PrintingFailedUi {
            get {
                return ResourceManager.GetString("PrintingFailedUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing..
        /// </summary>
        internal static string PrintInProgressUi {
            get {
                return ResourceManager.GetString("PrintInProgressUi", resourceCulture);
            }
        }
    }
}
