[{DATABASE_NAME}].[dbo].[dist_batch]
SELECT [dist_batch_id]
		,[branch_id]
		,[no_cards]
		,ToDateTimeOffset([date_created], DATENAME(tz, SYSDATETIMEOFFSET())) as [date_created]
		,[dist_batch_reference]
		,[card_issue_method_id]
		,[dist_batch_type_id]
		,[issuer_id]
FROM [{SOURCE_DATABASE_NAME}].[dbo].[dist_batch]